package com.mac.arbitrator.annotation;

import com.mac.arbitrator.annotation.AutoCodeGeneratorService;
import com.mac.arbitrator.util.SpringContext;
import jakarta.persistence.PrePersist;

import java.lang.reflect.Field;

public class AutoGeneratedCodeListener {

    @PrePersist
    public void generate(Object entity) {
        AutoCodeGeneratorService codeService = SpringContext.getBean(AutoCodeGeneratorService.class);

        for (Field field : entity.getClass().getDeclaredFields()) {
            if (!field.isAnnotationPresent(AutoGeneratedCode.class)) continue;

            try {
                field.setAccessible(true);
                if (field.get(entity) != null) continue;

                AutoGeneratedCode config = field.getAnnotation(AutoGeneratedCode.class);
                String value = codeService.generateCode(config.prefix(), config.sequence());
                field.set(entity, value);

            } catch (Exception e) {
                throw new RuntimeException("Failed to generate code", e);
            }
        }
    }
}
