package com.mac.arbitrator.entity;

import com.mac.arbitrator.annotation.AutoGeneratedCode;
import com.mac.arbitrator.annotation.AutoGeneratedCodeListener;
import com.mac.arbitrator.entity.enums.CaseStatus;
import com.mac.arbitrator.entity.enums.FormStatus;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "legal_case",uniqueConstraints = {
        @jakarta.persistence.UniqueConstraint(columnNames = "id")
})
@EntityListeners(AutoGeneratedCodeListener.class)
public class LegalCase {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "admission_form_id", nullable = false)
    private Long admissionFormId;

    @Column(nullable = false)
    @AutoGeneratedCode(prefix = "ABBR",sequence = "case_seq")
    private String caseNo;

    private String section17DocPath;

    private String statementOfClaimPath;

    private String additionalDocumentPath;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false , columnDefinition = "VARCHAR(20) DEFAULT 'DRAFT'")
    private CaseStatus status;

    @Column(nullable = false)
    private Instant createdAt;

    @Column(nullable = false)
    private String createdByName;

    private Instant updatedAt;

    private Long updatedById;

    private String updatedByName;

}
