package com.mac.arbitrator.entity;


import com.mac.arbitrator.annotation.AutoGeneratedCode;
import com.mac.arbitrator.annotation.AutoGeneratedCodeListener;
import com.mac.arbitrator.entity.enums.FormStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "mediation_form",uniqueConstraints = {
        @jakarta.persistence.UniqueConstraint(columnNames = "id")
})
@EntityListeners(AutoGeneratedCodeListener.class)
public class MediationForm {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @AutoGeneratedCode(prefix = "MED",sequence = "med_seq")
    @Column(name = "mediation_form_no", nullable = false)
    private String mediationFormNo;

    @Column(name = "default_clause", nullable = false)
    private String defaultClause;

    @Column(name = "jurisdiction_id", nullable = false)
    private Long jurisdictionId;

    @Column(name = "jurisdiction_name", nullable = false)
    private String jurisdictionName;

    @Column(name = "arbitration_clause", nullable = false)
    private String arbitrationClause;

    @Column(name = "relief_sought", nullable = false)
    private String reliefSought;

    @Column(name = "dispute_amount", nullable = false)
    private Float disputeAmount;

    @Column(name = "dispute_date")
    private LocalDate disputeDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false , columnDefinition = "VARCHAR(20) DEFAULT 'DRAFT'")
    private FormStatus status;

    @Column(nullable = false)
    private LocalDate createdAt;
}
