package com.mac.arbitrator.dto.response.mini;

import com.mac.arbitrator.annotation.AutoGeneratedCode;
import com.mac.arbitrator.entity.enums.CaseStatus;
import com.mac.arbitrator.entity.enums.HearingStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class LegalCaseMniResponseDto {
    private Long id;
    private String caseNo;
    private String section17DocPath;
    private String statementOfClaimPath;
    private String additionalDocumentPath;
    private CaseStatus status;
    private String claimants;
    private String respondants;
    private HearingStatus overAllHearingStatus;
    private Instant createdAt;
    private String createdByName;
    private Instant updatedAt;
    private Long updatedById;
    private String updatedByName;
}
